#!/usr/bin/env php
<?php
/*
 * MIT License
 *
 * Copyright (c) 2021-2023 machinateur
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

// Define application/metadata constants.
include 'meta.php';

if (false === in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo PHP_EOL
        . sprintf('This application may only be invoked from a command line, got "%s".', PHP_SAPI)
        . PHP_EOL;

    exit(1);
}

require_once __DIR__ . '/vendor/autoload.php';

use Machinateur\ChromeTabTransfer\Command\CheckEnvironment;
use Machinateur\ChromeTabTransfer\Command\LegacyCopyTabsCommand;
use Machinateur\ChromeTabTransfer\Command\CopyTabsFromAndroid;
use Machinateur\ChromeTabTransfer\Command\CopyTabsFromIphone;
use Symfony\Component\Console\Application;
use Symfony\Component\EventDispatcher\EventDispatcher;

$isCompatibilityMode = true == $_SERVER['COMPATIBILITY_MODE'] ?? $_ENV['COMPATIBILITY_MODE'] ?? false;
$isCompatibilityMode = true; // TODO: Remove this line.

$commands = [
    new CheckEnvironment(),
    new CopyTabsFromAndroid(),
    new CopyTabsFromIphone(),
];

$application = new Application(APP_NAME, APP_VERSION);
$dispatcher  = new EventDispatcher();

// To allow still running the old legacy `copy-tabs` command, some additional steps are necessary.
if ($isCompatibilityMode) {
    $command    = new LegacyCopyTabsCommand();
    $commands[] = $command;

    $dispatcher->addSubscriber($command);

    unset($command);
}

$application->setDispatcher($dispatcher);
$application->addCommands($commands);

// Leave only $application and $dispatcher as global variables.
unset($isCompatibilityMode, $commands);

$application->run();
